新增加openruyi基础镜像制作guix镜像

diff --git a/guix-cross-build b/guix-cross-build
--- a/guix-cross-build
+++ b/guix-cross-build
@@ -11,6 +11,7 @@ URL_PATH_PARTS=$(echo "$URL_WITHOUT_PROTOCOL" | cut -d '/' -f 2-)
 URL_REPO_CORE=$(echo "$URL_PATH_PARTS" | cut -d '/' -f 1,2 | sed 's#/$##')
 REPO=$(echo $URL_REPO_CORE | cut -d '/' -f 2 | sed 's/\.git$//')
 REPO_URL="${URL_PROTOCOL}${URL_DOMAIN}/${URL_REPO_CORE}"
+OS_ID=$(grep ^ID= /etc/os-release | cut -d'"' -f2)
 
 retry() {
     local max_attempts=$1; shift
@@ -49,6 +50,9 @@ if [[ "${REPO}" == "rvck" ]];then
 elif [[ "${REPO}" == "rvck-olk" ]];then
     kernel_config="openeuler_defconfig"
     dracut_driver_add="--add-drivers "k1-emac""
+elif [[ "${REPO}" == "linux" ]];then
+    kernel_config="defconfig"
+    dracut_driver_add=""
 else
     echo "kernel_config未匹配到有效信息"
     exit 1
@@ -139,8 +143,23 @@ mount --bind /run ${initramfs_chroot}/run
 mount -t proc proc ${initramfs_chroot}/proc
 mount -t sysfs sys ${initramfs_chroot}/sys
 
-retry 10 30 dnf group install -y "Minimal Install" --forcearch riscv64 --installroot ${initramfs_chroot}
-retry 10 30 dnf install -y dracut dracut-network nfs-utils --forcearch riscv64 --installroot ${initramfs_chroot} 
+if [[ ${OS_ID} == "openEuler" ]]; then
+    retry 10 30 dnf group install -y "Minimal Install" --forcearch riscv64 --installroot ${initramfs_chroot}
+    retry 10 30 dnf install -y dracut dracut-network nfs-utils --forcearch riscv64 --installroot ${initramfs_chroot} 
+elif [[ ${OS_ID} == "openruyi" ]]; then
+    cat >> /etc/yum.repos.d/openruyi.repo <<EOF
+[Base-rva23]
+name=openruyi Base rva23
+baseurl=https://boat.openruyi.cn/unstable/rva23
+enabled=1
+gpgcheck=0
+EOF
+    retry 10 30 dnf install -y openruyi-minimal dracut dracut-network nfs-utils --forcearch riscv64 --installroot ${initramfs_chroot} --use-host-config --repoid=Base-rva23
+else
+    echo "Error: wrong OS_ID"
+    exit 1
+fi
+
 cp -r ${RESULT_PATH}/${git_commit}/lib/modules/${module_dir_name} ${initramfs_chroot}/lib/modules/
 chroot ${initramfs_chroot} /bin/bash -c "dracut /root/initramfs.img --no-hostonly --add \" nfs network base \" ${dracut_driver_add} --kver ${module_dir_name} && md5sum /root/initramfs.img > /root/initramfs.img.md5sum"
 md5sum ${RESULT_PATH}/${git_commit}/Image > ${RESULT_PATH}/${git_commit}/Image.md5sum
